<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Bestellsystem_Lieferdienst_Server</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MySql.Data" Version="9.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Client-Server_Code_Library\Client-Server_Code_Library.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="BL\Datatypes\" />
    </ItemGroup>

</Project>
