-- MySQL Script generated by MySQL Workbench
-- Mon Jun 16 09:12:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Deliveryservice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Deliveryservice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Deliveryservice` DEFAULT CHARACTER SET utf8 ;
USE `Deliveryservice` ;

-- -----------------------------------------------------
-- Table `Deliveryservice`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `productdescription` TEXT(1000) NULL,
  `price` DECIMAL NOT NULL,
  `image` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`productID`),
  UNIQUE INDEX `ProduktID_UNIQUE` (`productID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`Usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Usertype` (
  `usertypeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usertypeID`),
  UNIQUE INDEX `usertypeID_UNIQUE` (`usertypeID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Address` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(80) NOT NULL,
  `postzip` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `housenr` VARCHAR(10) NOT NULL,
  `apartmentnr` INT NULL,
  PRIMARY KEY (`addressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `usertypeID` INT NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `address_addressID` INT NULL,
  PRIMARY KEY (`userID`, `usertypeID`),
  UNIQUE INDEX `UserID_UNIQUE` (`userID` ASC) ,
  INDEX `fk_user_user_type1_idx` (`usertypeID` ASC) ,
  INDEX `fk_User_Address1_idx` (`address_addressID` ASC) ,
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`usertypeID`)
    REFERENCES `Deliveryservice`.`Usertype` (`usertypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Address1`
    FOREIGN KEY (`address_addressID`)
    REFERENCES `Deliveryservice`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`Productgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Productgroup` (
  `productgroupID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`productgroupID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`Product_has_Productgroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Product_has_Productgroup` (
  `productID` INT NOT NULL,
  `productgroupID` INT NOT NULL,
  PRIMARY KEY (`productID`, `productgroupID`),
  INDEX `fk_Produkt_has_Produktgruppe_Produktgruppe1_idx` (`productgroupID` ASC) ,
  INDEX `fk_Produkt_has_Produktgruppe_Produkt1_idx` (`productID` ASC) ,
  CONSTRAINT `fk_Produkt_has_Produktgruppe_Produkt1`
    FOREIGN KEY (`productID`)
    REFERENCES `Deliveryservice`.`Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produkt_has_Produktgruppe_Produktgruppe1`
    FOREIGN KEY (`productgroupID`)
    REFERENCES `Deliveryservice`.`Productgroup` (`productgroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `User_userID` INT NULL,
  `state` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `address` VARCHAR(1000) NULL,
  PRIMARY KEY (`orderID`),
  UNIQUE INDEX `orderID_UNIQUE` (`orderID` ASC) ,
  INDEX `fk_Order_User1_idx` (`User_userID` ASC) ,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `Deliveryservice`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deliveryservice`.`Order_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Deliveryservice`.`Order_has_Product` (
  `Order_orderID` INT NOT NULL,
  `product_productD` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`Order_orderID`, `product_productD`),
  INDEX `fk_Produkt_has_Bestellung_Produkt1_idx` (`product_productD` ASC) ,
  INDEX `fk_Order_has_Product_Order1_idx` (`Order_orderID` ASC) ,
  CONSTRAINT `fk_Produkt_has_Bestellung_Produkt1`
    FOREIGN KEY (`product_productD`)
    REFERENCES `Deliveryservice`.`Product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_Order1`
    FOREIGN KEY (`Order_orderID`)
    REFERENCES `Deliveryservice`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
