<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RootNamespace>Bestellsystem_Lieferdienst</RootNamespace>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="DAL\**" />
      <EmbeddedResource Remove="DAL\**" />
      <None Remove="DAL\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="PL\Consumer\SignupUserControl.cs">
            <SubType>UserControl</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="System.Drawing.Common" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Client-Server_Code_Library\Client-Server_Code_Library.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="PL\Admin\" />
    </ItemGroup>

</Project>